/* =========================================================================
   PRODUCTS.JS
   All product data lives here as one PRODUCTS array. Every part of the
   site (homepage, catalog, search, product modal) reads from it.

   TO ADD A PRODUCT
   Easiest: open add-product.html, fill the form, hit Generate, paste the
   result before the closing "]" below.

   Or copy any object below, give it a new unique "id", and edit:
     id            unique short code (kebab-case), never change once used
     name          product name
     brand         must match an id in SITE_CONFIG.brands (js/config.js)
     category      must match an id in SITE_CONFIG.categories (js/config.js)
     subcategory   short label, shown in the product's details table
     description   1-3 sentence description
     image         main product photo (URL) — PLACEHOLDER, replace with real photos
     gallery       optional — extra photo URLs shown in the product view
     featured      true/false — show on homepage "Featured Products"
     bestseller    true/false — show on homepage "Best Sellers"
     dateAdded     "YYYY-MM-DD", used by the "Newest" sort
     tags          lowercase keywords, used by search
   ========================================================================= */

const PRODUCTS = [
  {
    id: "refinex-botx-100",
    name: "REFINEX Botulinum Toxin (100 Units)",
    brand: "refinex",
    category: "botox",
    subcategory: "Standard Vial",
    description: "A standard-vial botulinum toxin type A formulation for the treatment of dynamic facial wrinkles and hyperhidrosis.",
    image: "https://dermatologyhubegypt.com/cdn/shop/files/Refinex100u.png?v=1784661289&width=3840",
    gallery: ["https://beautimedi.com/wp-content/uploads/2026/02/WhatsApp-Image-2026-02-13-at-5.54.35-PM-1.jpeg"],
    featured: true,
    bestseller: true,
    dateAdded: "2026-01-10",
    tags: ["botox", "toxin", "wrinkles", "hyperhidrosis", "100 units"]
  },
  {
    id: "metox-100u",
    name: "METOX Botulinum Toxin (100 Units)",
    brand: "metox",
    category: "botox",
    subcategory: "Standard Vial",
    description: "A 100-unit botulinum toxin type A vial formulated for precise treatment of dynamic wrinkles.",
    image: "https://derma-solution.com/wp-content/uploads/2023/09/metox-2.jpg",
    gallery: ["https://opalnirvana.com/wp-content/uploads/2025/08/Metox_100U_T.jpg"],
    featured: false,
    bestseller: true,
    dateAdded: "2026-01-15",
    tags: ["botox", "toxin", "wrinkles", "100 units"]
  },
  {
    id: "dysport-500u",
    name: "Dysport Botulinum Toxin (500 Units)",
    brand: "dysport",
    category: "botox",
    subcategory: "Standard Vial",
    description: "A widely used botulinum toxin type A formulation for wrinkle treatment and management of excessive sweating.",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT-NQZVmplKW4S5LyOaf_k91GqHJTdnLw15YRGIESW-NA&s=10",
    gallery: ["https://dkud4u09qff41.cloudfront.net/Products/e3911f49-552e-4765-9759-004a57cb6a7f.jpeg"],
    featured: true,
    bestseller: true,
    dateAdded: "2026-01-20",
    tags: ["botox", "toxin", "wrinkles", "hyperhidrosis", "500 units"]
  },
  {
    id: "evetox-100unit",
    name: "Eve Tox Botulinum Toxin (100 Units)",
    brand: "evetox",
    category: "botox",
    subcategory: "Standard Vial",
    description: "A botulinum toxin type A vial designed to smooth dynamic facial lines and refresh expression.",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTfabC8Frew82yO9hHsdDtcOzvitcPxDZ5a1_rDWQndDKOzFBztQ1RPr7U&s=10",
    gallery: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSF4sSpCnsEpB4TAzzmQmc-ntaCzA9fhNOW-x9ttXu3ixIYcC2JNv5ZNAI&s=10"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-01-25",
    tags: ["botox", "toxin", "wrinkles", "100 units"]
  },
  {
    id: "nabota-100unit",
    name: "Nabota Botulinum Toxin (100 Units)",
    brand: "nabota",
    category: "botox",
    subcategory: "Standard Vial",
    description: "A 100-unit botulinum toxin type A formulation for dynamic wrinkle correction.",
    image: "https://celmade.co/cdn/shop/files/imgi_186_nabota-100units.jpg?v=1766416285",
    gallery: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS0T9V-ug-fp9rAhFXOnVhVtz3nk6p7OBjBnVLIWt-vRz-6kzhzzrzhX2Ox&s=10"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-01-30",
    tags: ["botox", "toxin", "wrinkles", "100 units"]
  },
  {
    id: "demure-ultra-10ml",
    name: "Demure Ultra Dermal Filler (10 ml)",
    brand: "demure",
    category: "dermal-fillers",
    subcategory: "Volumizing & Contouring",
    description: "A hyaluronic-acid gel designed for facial and body volumizing and contouring.",
    image: "https://cosmohub1.com/wp-content/uploads/2025/03/1000028877-600x600.jpg",
    gallery: ["https://mamak-paziresh.ir/wp-content/uploads/2025/10/WhatsApp-Image-2025-12-24-at-1.17.34-PM.jpeg"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-02-04",
    tags: ["filler", "hyaluronic acid", "volumizing", "10 ml"]
  },
  {
    id: "demure-grand-10ml",
    name: "Demure Grand Dermal Filler (10 ml)",
    brand: "demure",
    category: "dermal-fillers",
    subcategory: "Volumizing & Contouring",
    description: "A higher-volume hyaluronic-acid gel for facial and body contouring procedures.",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS9uacRkyHynzV51BSNfz6KgSum0An09IlLstJzpv34oD4lwwNFjVF6fDRw&s=10",
    gallery: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ25sJjG2U_37zNHu4MVuxlaFhZxy10uHVsqMVwjjZC_LsNg3Qr448ZEzA&s=10"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-02-09",
    tags: ["filler", "hyaluronic acid", "volumizing", "10 ml"]
  },
  {
    id: "dermofil-hv",
    name: "Dermofil HV Dermal Filler (1 ml)",
    brand: "dermofil",
    category: "dermal-fillers",
    subcategory: "High Viscosity",
    description: "A high-viscosity hyaluronic-acid filler intended for deep structural placement.",
    image: "https://cosmohub1.com/wp-content/uploads/2025/03/1000034631-scaled.jpg",
    gallery: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT76meGl3i_XLzxgxMkzRhlnB3xGqWVCdfogbk3fwdHHvZPkZaRdkKLiNP9&s=10"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-02-14",
    tags: ["filler", "high viscosity", "hyaluronic acid", "1 ml"]
  },
  {
    id: "dermofil-volumizer",
    name: "Dermofil Volumizer (1 ml)",
    brand: "dermofil",
    category: "dermal-fillers",
    subcategory: "Volumizer",
    description: "A cohesive volumizing gel formulated for mid-face and structural support.",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRsofYuLDW-DyqheVonBLS3OM__cqlmWcpl8DAlXdyiaNLD-xYtm5-VdAF3&s=10",
    gallery: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRZLRja4-wlyg207v1ylmz1wDIBk--aoJ7xF2P8DMODyg&s=10"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-02-19",
    tags: ["filler", "volumizer", "hyaluronic acid", "1 ml"]
  },
  {
    id: "hyamax-10ml-contour",
    name: "Hyamax Contour White Label (10 ml)",
    brand: "hyamax",
    category: "dermal-fillers",
    subcategory: "Contour",
    description: "A white-label hyaluronic-acid gel for facial contouring and body sculpting.",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTEMeJ66a7pi-j4j5anJNU8-P4LoyhVt1S_Tj3yPi2KvGkQ5ECWLoeqARw8&s=10",
    gallery: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT7PZb4gycel6bf9vK3C2qRvOmK2u2TTU-fjmvp_Pngv1KKuS9kD_8Y1qQ&s=10"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-02-24",
    tags: ["filler", "contour", "white label", "10 ml"]
  },
  {
    id: "hyamax-10ml-contour-c",
    name: "Hyamax Contour C (10 ml)",
    brand: "hyamax",
    category: "dermal-fillers",
    subcategory: "Contour",
    description: "A hyaluronic-acid gel formulated for definition of larger contouring areas.",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR4BxTAfeNHlhF5JmSqhrvjXmW1AP15MXWMxBIwq9aZY4McLtIzpcVrxVg&s=10",
    gallery: ["https://cosmohub1.com/wp-content/uploads/2025/07/1000028868-600x600.jpg"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-03-01",
    tags: ["filler", "contour", "body", "10 ml"]
  },
  {
    id: "hyamax-10ml-volumizer",
    name: "Hyamax Volumizer (10 ml)",
    brand: "hyamax",
    category: "dermal-fillers",
    subcategory: "Volumizer",
    description: "A high-capacity volumizing hyaluronic-acid gel for facial and body use.",
    image: "https://api.yasso.store/img.php?src=uploads%2Fprod_1786784293_32eeaae233b823de.jpg&w=400",
    featured: false,
    bestseller: false,
    dateAdded: "2026-03-06",
    tags: ["filler", "volumizer", "hyaluronic acid", "10 ml"]
  },

// اللي تحت ده مفيش صوره لسه
  {
    id: "master-treat-extreme-black",
    name: "Master Treat Extreme (Black) (1 ml)",
    brand: "master-treat",
    category: "dermal-fillers",
    subcategory: "Extreme Density",
    description: "An extreme-density gel formulated for large-area contouring and definition.",
    image: "https://picsum.photos/seed/aesthera-master-treat-extreme-black/700/860",
    gallery: ["https://picsum.photos/seed/aesthera-master-treat-extreme-black-b/700/860"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-03-11",
    tags: ["filler", "extreme density", "contour", "1 ml"]
  },
  {
    id: "audrey-m-blue",
    name: "Audrey Medium Viscosity (Blue) (1 ml)",
    brand: "audrey",
    category: "dermal-fillers",
    subcategory: "Medium Viscosity",
    description: "A medium-viscosity hyaluronic-acid filler for balanced volumizing results.",
    image: "https://koreanfillers.com/wp-content/uploads/2024/08/Audrey-M-1mL.png",
    featured: false,
    bestseller: false,
    dateAdded: "2026-03-16",
    tags: ["filler", "medium viscosity", "1 ml"]
  },
  {
    id: "audrey-h-black",
    name: "Audrey High Viscosity (Black) (1 ml)",
    brand: "audrey",
    category: "dermal-fillers",
    subcategory: "High Viscosity",
    description: "A high-viscosity hyaluronic-acid filler for structural definition.",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQf0sUKWfvtwjN4vp7kTutEfrRrlvgC9b3o6Wiq5dCXdg&s=10",
    gallery: ["https://faroha.com/wp-content/uploads/2022/08/lidoAn.jpg"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-03-21",
    tags: ["filler", "high viscosity", "1 ml"]
  },
  {
    id: "revolax-subq",
    name: "Revolax Sub-Q (1 ml)",
    brand: "revolax",
    category: "dermal-fillers",
    subcategory: "Sub-Q",
    description: "A dense hyaluronic-acid gel formulated for deep sub-dermal volumizing.",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSXi2j6rvQNLU2dn0J7BCkEWrxb7TzkruJrZcvPoKX21Q&s=10",
    gallery: ["https://jolifill.de/cdn/shop/files/REVOLAX-SUB-Q-LIDOCAINE-1-X-1_1ML-SPRITZE-VERPACKUNG.webp?v=1769093251"],
    featured: true,
    bestseller: true,
    dateAdded: "2026-03-26",
    tags: ["filler", "sub-q", "hyaluronic acid", "1 ml"]
  },
  {
    id: "master-treat-standard-white",
    name: "Master Treat Standard (White) (1 ml)",
    brand: "master-treat",
    category: "dermal-fillers",
    subcategory: "Standard Density",
    description: "A standard-density hyaluronic-acid gel for general facial revitalization and fine-line improvement.",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRUU-gztWU4BZuqpiZlUXRjFIlJ47XBIrC6vF_UTWsg1Q&s=10",
    gallery: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQzXFRkBe8BlUOgiTFQLBko0jYWpWcrvYqWEfdTIvZqhQ&s=10"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-03-31",
    tags: ["filler", "standard density", "1 ml"]
  },
  {
    id: "deneb-classic-h",
    name: "DeneB Classic-H (1 ml)",
    brand: "deneb",
    category: "dermal-fillers",
    subcategory: "High Density",
    description: "A high-density filler intended for revitalization and improvement of facial lines.",
    image: "https://jolifill.de/cdn/shop/files/DENEB-CLASSIC-H-1-X-10ML.webp?v=1769099044",
    gallery: ["https://moryskin.com/media/image/0d/7e/95/DeneBClassic-H_MorySkin-png_600x600.png"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-04-05",
    tags: ["filler", "high density", "1 ml"]
  },
  {
    id: "sedyfill-60cc",
    name: "Sedyfill 60CC (60 cc)",
    brand: "sedyfill",
    category: "dermal-fillers",
    subcategory: "Body Contouring",
    description: "A large-format hyaluronic-acid gel for body contouring and volumizing.",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQEXEtzcchvgwrHnJ3ac8GRIkl9hmDaYj_BjDF1ACXbBg&s=10",
    gallery: ["https://shopme365.com/image/cache/wkseller/23229/e4-600x315w.jpg"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-04-10",
    tags: ["filler", "body", "contouring", "60 cc"]
  },
  {
    id: "sedyfill-80cc",
    name: "Sedyfill 80CC (80 cc)",
    brand: "sedyfill",
    category: "dermal-fillers",
    subcategory: "Body Contouring",
    description: "A large-format hyaluronic-acid gel for body contouring and volumizing.",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT3jV8pUdiT6gTGEZYX15dbH48DdPgmw32Hl67E-5VF9A&s=10",
    gallery: ["https://cdn.pddmooncdn.com/uploads/161395/cart/resources/20250813/F77BB62F-5F31-A751-6E97-3A896CA393CB.jpg"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-04-15",
    tags: ["filler", "body", "contouring", "80 cc"]
  },
  {
    id: "sedyfill-100cc",
    name: "Sedyfill 100CC (100 cc)",
    brand: "sedyfill",
    category: "dermal-fillers",
    subcategory: "Body Contouring",
    description: "A large-format hyaluronic-acid gel for extensive body contouring procedures.",
    image: "https://skindermalfiller.com/cdn/shop/files/sedyfill100-thumbnail-4.jpg?v=1787123309",
    gallery: ["https://kstations.com/cdn/shop/files/SEDY_FILL_100cc_1_Vial.webp?v=1768271686"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-04-20",
    tags: ["filler", "body", "contouring", "100 cc"]
  },
  {
    id: "celosome-soft",
    name: "Celosome Soft Density (1 ml)",
    brand: "celosome",
    category: "dermal-fillers",
    subcategory: "Soft Density",
    description: "A soft-density filler suited to superficial lines around the eyes and lips.",
    image: "https://fillerfyco.com/wp-content/uploads/2026/07/wholesaleclosomesoft-465x465.webp",
    gallery: ["https://i0.wp.com/www.pharmacoline.com/wp-content/uploads/2023/10/12138-Celosome-Soft.jpg?fit=1000%2C1000&ssl=1"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-04-25",
    tags: ["filler", "soft density", "fine lines", "1 ml"]
  },
  {
    id: "celosome-mid",
    name: "Celosome Medium Density (1 ml)",
    brand: "celosome",
    category: "dermal-fillers",
    subcategory: "Medium Density",
    description: "A medium-density filler for balanced facial revitalization.",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR8g72gFmS8PxrhQeY1hSXNbGlcpSSF4_VxzUR1EXf66w&s=10",
    gallery: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ31E9G0fB4loBuVol2dixqEmpj3XsIqLiZbVBEfVZE-A&s=10"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-04-30",
    tags: ["filler", "medium density", "1 ml"]
  },
  {
    id: "celosome-strong",
    name: "Celosome Strong Density (1 ml)",
    brand: "celosome",
    category: "dermal-fillers",
    subcategory: "Strong Density",
    description: "A strong-density filler formulated for larger-area contouring and definition.",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSNk5tfatJkVq3wCEZdyMsp5tQceCulLrU6bCrcFmPqsPNmPIGlSjpdCWXy&s=10",
    gallery: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZOuOSlne0ybmsFkAoEIbE-u1UW547iE-ol1vje_s1gbuVUoTMmvdOv5tE&s=10"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-05-05",
    tags: ["filler", "strong density", "contour", "1 ml"]
  },
  {
    id: "celosome-implant",
    name: "Celosome Implant Grade (1 ml)",
    brand: "celosome",
    category: "dermal-fillers",
    subcategory: "Implant Grade",
    description: "An implant-grade filler intended for deep structural placement.",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQRE7dP4ktRI7sAT7UCvdHnf2elF2wbKhHpCCwDtmKoRQ&s=10",
    gallery: ["https://meamoshop.com/wp-content/uploads/2025/02/Celosome-Impact-with-Syringe.webp"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-05-10",
    tags: ["filler", "implant grade", "1 ml"]
  },
  {
    id: "revolax-deep",
    name: "Revolax Deep (1 ml)",
    brand: "revolax",
    category: "dermal-fillers",
    subcategory: "Deep Density",
    description: "A deep-density hyaluronic-acid gel for superficial-to-deep line correction around the eyes and lips.",
    image: "https://prpmed.de/1175-thickbox_default/revolax-deep-with-lidocaine-11-ml.jpg",
    gallery: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRNng4UF9NGSUqaHF13LSNrvoSnc4jQBkfrSK0p1STMDeCcFnxiPhhIlAM&s=10"],
    featured: false,
    bestseller: true,
    dateAdded: "2026-05-15",
    tags: ["filler", "deep density", "1 ml"]
  },
  {
    id: "sculptra-white",
    name: "Sculptra (PLLA) (1 vial)",
    brand: "sculptra",
    category: "dermal-fillers",
    subcategory: "Poly-L-Lactic Acid",
    description: "A poly-L-lactic acid (PLLA) biostimulator for gradual, long-lasting collagen stimulation.",
    image: "https://res.cloudinary.com/dbeuhr91i/image/upload/f_webp,q_auto,dpr_auto,c_limit/v1778511839/products/a3as78d1ge5f2dibem9k.jpg",
    gallery: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR0g8LKplqzFKdQqRHOLx9PsfUlDS-stXamzMM97_C8SPKoBDqBomhhCa4&s=10"],
    featured: true,
    bestseller: true,
    dateAdded: "2026-05-20",
    tags: ["filler", "plla", "collagen stimulator", "1 vial"]
  },
   {
    id: "olidia-plla",
    name: "Olidia PLLA Bio-stimulator (1 vial)",
    brand: "olidia",
    category: "dermal-fillers",
    subcategory: "PLLA Bio-stimulator",
    description: "A PLLA-based biostimulator formulated for long-lasting collagen stimulation.",
    image: "https://celmade.net/wp-content/uploads/2024/11/olidia-2.jpg",
    gallery: ["https://kstations.com/cdn/shop/files/OLIDIA_PLLA_365mg_1_Vial.png?v=1764807857"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-05-25",
    tags: ["filler", "plla", "collagen stimulator", "1 vial"]
  },
  {
    id: "vom-intense",
    name: "VOM Intense HA Density (1 ml)",
    brand: "vom",
    category: "dermal-fillers",
    subcategory: "Intense HA Density",
    description: "An intense-density hyaluronic-acid filler for pronounced volumizing and contouring.",
    image: "https://celmade.co/cdn/shop/files/imgi_222_vom-o-intensive-brunodermalfillercom-562120.jpg?v=1766416286",
    featured: false,
    bestseller: false,
    dateAdded: "2026-05-30",
    tags: ["filler", "intense density", "hyaluronic acid", "1 ml"]
  },
  {
    id: "liporase-1500iu",
    name: "Liporase Hyaluronidase (1500 IU)",
    brand: "premium",
    category: "dermal-fillers",
    subcategory: "Hyaluronidase",
    description: "A hyaluronidase enzyme preparation used to dissolve hyaluronic-acid filler.",
    image: "https://derma-solution.com/wp-content/uploads/2021/08/liporase-bg.png",
    gallery: ["https://derma-solution.com/wp-content/uploads/2026/08/liporase-3-1.png"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-06-04",
    tags: ["hyaluronidase", "dissolving enzyme", "1500 iu"]
  },
  {
    id: "premium-2ml",
    name: "Premium Filler (2 ml)",
    brand: "premium",
    category: "dermal-fillers",
    subcategory: "Volumizing & Contouring",
    description: "A hyaluronic-acid gel designed for facial volumizing and contouring.",
    image: "https://i0.wp.com/www.pharmacoline.com/wp-content/uploads/2023/02/image-19.jpeg?w=1024&ssl=1",
    gallery: ["https://img.shr-germany-onlineshop.de/27676-medium_default/chaeum-premium-2-hyaluron-filler-2-stk-a-11-ml.webp"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-06-09",
    tags: ["filler", "hyaluronic acid", "2 ml"]
  },
  {
    id: "hyamax-lips-1ml",
    name: "Hyamax Lips (1 ml)",
    brand: "hyamax",
    category: "dermal-fillers",
    subcategory: "Fine Lines",
    description: "A hyaluronic-acid gel formulated for lip enhancement and superficial lines around the mouth.",
    image: "https://i0.wp.com/pharmadiv.co.za/wp-content/uploads/2026/06/300Wx300H-106756-01.png?fit=300%2C300&ssl=1",
    featured: false,
    bestseller: false,
    dateAdded: "2026-06-14",
    tags: ["filler", "lips", "fine lines", "1 ml"]
  },
  {
    id: "richesse-soft-1ml",
    name: "Richesse Soft (1 ml)",
    brand: "richesse",
    category: "dermal-fillers",
    subcategory: "Fine Lines",
    description: "A soft-formulation filler for superficial lines around the eyes and lips.",
    image: "https://en.jdbio.com/cdn/shop/files/RichesseDeep2sy-2_393ddcd3-87b5-4a48-84e0-3f6318f2ce52.jpg?v=1744964238&width=1500",
    gallery: ["https://jdbioshop.com/cdn/shop/files/RichesseDeep-2.jpg?v=1745907182"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-06-19",
    tags: ["filler", "soft", "fine lines", "1 ml"]
  },
  {
    id: "richesse-deep-1ml",
    name: "Richesse Deep (1 ml)",
    brand: "richesse",
    category: "dermal-fillers",
    subcategory: "Revitalization",
    description: "A deep-formulation filler for facial revitalization and line improvement.",
    image: "https://jdbioshop.com/cdn/shop/files/RichesseDeep2sy-2_393ddcd3-87b5-4a48-84e0-3f6318f2ce52.jpg?v=1745907193",
    gallery: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQTu95C68ZnCjNIwjGlpZgu_FdKPs7FnpnXaVuy6DaXDrXApD8hBFZOrz-l&s=10"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-06-24",
    tags: ["filler", "deep", "revitalization", "1 ml"]
  },
  {
    id: "dermofil-volumizer-2ml",
    name: "Dermofil Volumizer (2 ml)",
    brand: "dermofil",
    category: "dermal-fillers",
    subcategory: "Volumizer",
    description: "A cohesive volumizing gel formulated for total-face contouring.",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS3G_T-05UqS4lN9Ndmw7HlvcnNztlNuCZSEwGQpDap_Pzlr0f8cZdDaAhU&s=10",
    featured: false,
    bestseller: false,
    dateAdded: "2026-06-29",
    tags: ["filler", "volumizer", "2 ml"]
  },
  {
    id: "vom-light",
    name: "VOM Light Viscosity (1 ml)",
    brand: "vom",
    category: "dermal-fillers",
    subcategory: "Light Viscosity",
    description: "A light-viscosity hyaluronic-acid gel for delicate facial areas.",
    image: "https://cdn.acecosm.com/products/vom-light-2-thumbnail.png?v=dd639d64",
    featured: false,
    bestseller: false,
    dateAdded: "2026-07-04",
    tags: ["filler", "light viscosity", "1 ml"]
  },
  {
    id: "hyamax-extra-deep-2ml",
    name: "Hyamax Extra Deep (2 ml)",
    brand: "hyamax",
    category: "dermal-fillers",
    subcategory: "Collagen Stimulator",
    description: "A long-lasting collagen-stimulating formulation for deep structural support.",
    image: "https://fillermsk.ru/_D4KkSwok11r_pFSADczBW3SU7g=/fit-in/1024x768/center/top/s.siteapi.org/d9e3899a37d35f9/img/h2g9eqmctgggs4cgggcc000gw4wccg.jpeg",
    featured: false,
    bestseller: false,
    dateAdded: "2026-07-09",
    tags: ["filler", "collagen stimulator", "deep", "2 ml"]
  },
  {
    id: "hyamax-extra-deep-2ml-red",
    name: "Hyamax Extra Deep Red (2 ml)",
    brand: "hyamax",
    category: "dermal-fillers",
    subcategory: "Collagen Stimulator",
    description: "A long-lasting collagen-stimulating formulation for deep structural support.",
    image: "https://hyamax.ru/wp-content/uploads/2025/05/003-hyamax-extra-deep-1024x1024.png",
    gallery: ["https://hyamax.ru/wp-content/uploads/2025/05/004-hyamax-extra-deep-1024x1024.png"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-07-14",
    tags: ["filler", "collagen stimulator", "deep", "2 ml"]
  },
  {
    id: "hyamax-volumizer-2ml",
    name: "Hyamax Volumizer (2 ml)",
    brand: "hyamax",
    category: "dermal-fillers",
    subcategory: "Volumizer",
    description: "A volumizing hyaluronic-acid gel for facial and body contouring.",
    image: "https://cosmohub1.com/wp-content/uploads/2025/07/1000028901.jpg",
    featured: false,
    bestseller: false,
    dateAdded: "2026-07-19",
    tags: ["filler", "volumizer", "2 ml"]
  },
  {
    id: "hyamax-caha-1ml",
    name: "Hyamax Calcium Hydroxyapatite (1 ml)",
    brand: "hyamax",
    category: "dermal-fillers",
    subcategory: "Calcium Hydroxyapatite",
    description: "A calcium-hydroxyapatite formulation for structural volumizing and contouring.",
    image: "https://beautimedi.com/wp-content/uploads/2026/02/WhatsApp-Image-2026-02-16-at-11.49.42-AM.jpeg",
    featured: false,
    bestseller: false,
    dateAdded: "2026-07-24",
    tags: ["filler", "calcium hydroxyapatite", "1 ml"]
  },

// اللي تحت ده مفيش صوره لسه
  {
    id: "volume-red-ha",
    name: "Volumizing HA Red (1 ml)",
    brand: "premium",
    category: "dermal-fillers",
    subcategory: "Volumizing HA",
    description: "A red-labeled volumizing hyaluronic-acid gel for facial contouring.",
    image: "",
    gallery: [],
    featured: false,
    bestseller: false,
    dateAdded: "2026-07-29",
    tags: ["filler", "volumizing", "hyaluronic acid", "1 ml"]
  },
  {
    id: "revolax-fine",
    name: "Revolax Fine (1 ml)",
    brand: "revolax",
    category: "dermal-fillers",
    subcategory: "Fine Viscosity",
    description: "A fine-viscosity filler formulated for superficial fine lines.",
    image: "https://e-fillers.com/storage/uploads/products/revolaxtm-fine-lidocaine-11ml/1674815235055_27_1.webp",
    gallery: ["https://shopme365.com/image/cache/wkseller/23229/r5-550x550.jpeg"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-08-03",
    tags: ["filler", "fine viscosity", "fine lines", "1 ml"]
  },
  {
    id: "eptq-10ml",
    name: "E.P.T.Q Large Volume (10 ml)",
    brand: "eptq",
    category: "dermal-fillers",
    subcategory: "Large Volume",
    description: "A large-volume hyaluronic-acid gel for extensive body contouring.",
    image: "https://www.twofaceaesthetics.com/cdn/shop/files/24-1041AnthonyHigginsCS_e.p.t.q._S500_7451.jpg?v=1724854559&width=1080",
    gallery: ["https://www.twofaceaesthetics.com/cdn/shop/files/24-1041AnthonyHigginsCS_e.p.t.q._S500_7918.jpg?v=1724854559&width=1214"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-08-08",
    tags: ["filler", "large volume", "body", "10 ml"]
  },
  {
    id: "richesse-glam-60ml",
    name: "Richesse Glam Body Filler (60 ml)",
    brand: "richesse",
    category: "dermal-fillers",
    subcategory: "Body Filler",
    description: "A large-format body filler formulated for body contouring procedures.",
    image: "https://elgohary-imed.com/wp-content/uploads/2024/09/Richesse-Glam-Fill-Classic-2-600x601.webp",
    gallery: ["https://elgohary-imed.com/wp-content/uploads/2024/09/richesse-glam-fill-classic-img.webp"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-08-13",
    tags: ["filler", "body", "glam", "60 ml"]
  },
  {
    id: "bella-ha-2x1ml-fine",
    name: "Bella HA Filler Fine (2 x 1 ml)",
    brand: "bella",
    category: "dermal-fillers",
    subcategory: "Fine",
    description: "A fine-formulation hyaluronic-acid filler for delicate facial areas.",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTYyjWLHhcOzTvD1O3Bg5ZLEWXPSKoFIzWrdZFQbZWbzxPX8vPSMumAz-yF&s=10",
    gallery: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRP0s2RFivtT3tSGEgjUkwUGP8JaVkrYkKwVEOBOMhX9AaWKqQdSZg_veLq&s=10"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-08-18",
    tags: ["filler", "bella", "fine", "2 x 1 ml"]
  },
  {
    id: "bella-ha-2x1ml-deep",
    name: "Bella HA Filler Deep (2 x 1 ml)",
    brand: "bella",
    category: "dermal-fillers",
    subcategory: "Deep",
    description: "A deep-formulation hyaluronic-acid filler for structural volumizing.",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRjHcU9cXTcIJbCasc1Pit4VcF341VW9P0-B8oDr41H4IbD4-6N0merbsY&s=10",
    gallery: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQzp4JFmVf5qT92e19ki8sNwiw7Jb0Mr6_yoOo0IZFcf1JbydVSP5v8tKo&s=10"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-08-23",
    tags: ["filler", "bella", "deep", "2 x 1 ml"]
  },
  {
    id: "bella-ha-2x1ml-derm",
    name: "Bella HA Filler Derm (2 x 1 ml)",
    brand: "bella",
    category: "dermal-fillers",
    subcategory: "Derm",
    description: "A dermal-layer hyaluronic-acid filler for mid-depth placement.",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQt4UD97NTH51fEJ8xiTido5u6_4DFsb4i4nv4SdSVJduLChQmiWCqdZi4&s=10",
    gallery: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS2ByQzZZ28TyWsPYjUHmV2lr6HA0jbkBKpFtdXZRFUZKgmkw0gTD109r8&s=10"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-08-28",
    tags: ["filler", "bella", "derm", "2 x 1 ml"]
  },
  {
    id: "bella-ha-1ml-fine",
    name: "Bella HA Filler Fine (1 ml)",
    brand: "bella",
    category: "dermal-fillers",
    subcategory: "Fine",
    description: "A fine-formulation hyaluronic-acid filler for delicate facial areas.",
    image: "https://ueeshop.ly200-cdn.com/u_file/UPBB/UPBB605/2608/25/products/FINE-1.jpg?x-oss-process=image/quality,q_100/resize,m_lfit,h_945,w_945",
    gallery: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQHWDIVvRrRrD6jmYwRyA2KSv7bXTXIDyNzVaWBa2UWGg&s=10"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-09-02",
    tags: ["filler", "bella", "fine", "1 ml"]
  },
  {
    id: "bella-ha-1ml-deep",
    name: "Bella HA Filler Deep (1 ml)",
    brand: "bella",
    category: "dermal-fillers",
    subcategory: "Deep",
    description: "A deep-formulation hyaluronic-acid filler for structural volumizing.",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRjHcU9cXTcIJbCasc1Pit4VcF341VW9P0-B8oDr41H4IbD4-6N0merbsY&s=10",
    gallery: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQzp4JFmVf5qT92e19ki8sNwiw7Jb0Mr6_yoOo0IZFcf1JbydVSP5v8tKo&s=10"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-09-07",
    tags: ["filler", "bella", "deep", "1 ml"]
  },
  {
    id: "bella-ha-1ml-derm",
    name: "Bella HA Filler Derm (1 ml)",
    brand: "bella",
    category: "dermal-fillers",
    subcategory: "Derm",
    description: "A dermal-layer hyaluronic-acid filler for mid-depth placement.",
    image: "https://ueeshop.ly200-cdn.com/u_file/UPBB/UPBB605/2608/25/products/DERM-1.jpg?x-oss-process=image/quality,q_100/resize,m_lfit,h_640,w_640",
    gallery: ["https://ueeshop.ly200-cdn.com/u_file/UPBB/UPBB605/2608/25/products/DERM-5.jpg?x-oss-process=image/quality,q_100/resize,m_lfit,h_640,w_640"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-09-12",
    tags: ["filler", "bella", "derm", "1 ml"]
  },
  {
    id: "bella-ha-2ml-fine",
    name: "Bella HA Filler Fine (2 ml)",
    brand: "bella",
    category: "dermal-fillers",
    subcategory: "Fine",
    description: "A fine-formulation hyaluronic-acid filler for delicate facial areas.",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTYyjWLHhcOzTvD1O3Bg5ZLEWXPSKoFIzWrdZFQbZWbzxPX8vPSMumAz-yF&s=10",
    gallery: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRP0s2RFivtT3tSGEgjUkwUGP8JaVkrYkKwVEOBOMhX9AaWKqQdSZg_veLq&s=10"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-09-17",
    tags: ["filler", "bella", "fine", "2 ml"]
  },
  {
    id: "bella-ha-2ml-deep",
    name: "Bella HA Filler Deep (2 ml)",
    brand: "bella",
    category: "dermal-fillers",
    subcategory: "Deep",
    description: "A deep-formulation hyaluronic-acid filler for structural volumizing.",
    image: "https://ueeshop.ly200-cdn.com/u_file/UPBB/UPBB605/2608/25/products/DEEP-1.jpg?x-oss-process=image/quality,q_100/resize,m_lfit,h_640,w_640",
    gallery: ["https://ueeshop.ly200-cdn.com/u_file/UPBB/UPBB605/2608/25/products/DEEP-5.jpg?x-oss-process=image/quality,q_100/resize,m_lfit,h_640,w_640"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-09-22",
    tags: ["filler", "bella", "deep", "2 ml"]
  },
  {
    id: "bella-ha-2ml-derm",
    name: "Bella HA Filler Derm (2 ml)",
    brand: "bella",
    category: "dermal-fillers",
    subcategory: "Derm",
    description: "A dermal-layer hyaluronic-acid filler for mid-depth placement.",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR-vS4k6U-Zqw0CJTT6DvOoatR3o0zV9c2WkmMULr2g5CPdj3Gt52Nl3sDO&s=10",
    gallery: ["https://ueeshop.ly200-cdn.com/u_file/UPBB/UPBB605/2608/25/products/DERM-5.jpg?x-oss-process=image/quality,q_100/resize,m_lfit,h_640,w_640"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-09-27",
    tags: ["filler", "bella", "derm", "2 ml"]
  },

  // اللي تحت ده برده مفيش صوره لسه
  {
    id: "bella-red-lips-2x1ml",
    name: "Bella Red Lips (2 x 1 ml)",
    brand: "bella",
    category: "dermal-fillers",
    subcategory: "Lips",
    description: "A hyaluronic-acid filler formulated specifically for lip enhancement.",
    image: "",
    gallery: [],
    featured: true,
    bestseller: true,
    dateAdded: "2026-10-02",
    tags: ["filler", "bella", "lips", "2 x 1 ml"]
  },
  {
    id: "bella-ha-10ml-subskin",
    name: "Bella HA Filler Sub-Skin (10 ml)",
    brand: "bella",
    category: "dermal-fillers",
    subcategory: "Sub-Skin",
    description: "A large-format sub-skin hyaluronic-acid filler for body use.",
    image: "https://ueeshop.ly200-cdn.com/u_file/UPBB/UPBB605/2608/25/products/SUB-SKIN-1.jpg?x-oss-process=image/quality,q_100/resize,m_lfit,h_945,w_945",
    gallery: ["https://ueeshop.ly200-cdn.com/u_file/UPBB/UPBB605/2510/27/products/subskin.jpg"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-10-07",
    tags: ["filler", "bella", "sub-skin", "body", "10 ml"]
  },
  {
    id: "bella-ha-10ml-deep",
    name: "Bella HA Filler Deep (10 ml)",
    brand: "bella",
    category: "dermal-fillers",
    subcategory: "Deep",
    description: "A large-format deep hyaluronic-acid filler for body contouring.",
    image: "https://www.easyimport.org/_next/image?url=https%3A%2F%2Fcdn.pazh.net%2Fpublic%2Fproduct%2Fbella-filler-deep-model%2F17846262293161d1-1080x1080.webp&w=3840&q=75",
    featured: false,
    bestseller: false,
    dateAdded: "2026-10-12",
    tags: ["filler", "bella", "deep", "body", "10 ml"]
  },
  {
    id: "bella-ha-10ml-derm",
    name: "Bella HA Filler Derm (10 ml)",
    brand: "bella",
    category: "dermal-fillers",
    subcategory: "Derm",
    description: "A large-format dermal-layer hyaluronic-acid filler for body use.",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS2X4jHOtPLGQWzKbhTIqcGdBEi7DVhxQLlVjsOzFlSdMqa9draDINVHH_z&s=10",
    gallery: ["https://ueeshop.ly200-cdn.com/u_file/UPBB/UPBB605/2608/25/products/DERM-5.jpg?x-oss-process=image/quality,q_100/resize,m_lfit,h_640,w_640"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-10-17",
    tags: ["filler", "bella", "derm", "body", "10 ml"]
  },
  {
    id: "bella-body-50ml",
    name: "Bella Body HA Filler (50 ml)",
    brand: "bella",
    category: "dermal-fillers",
    subcategory: "Body",
    description: "A large-format hyaluronic-acid body filler for extensive contouring.",
    image: "https://ueeshop.ly200-cdn.com/u_file/UPBB/UPBB605/2408/21/products/de6b2a61a8.png?x-oss-process=image/quality,q_100/resize,m_lfit,h_640,w_640",
    featured: false,
    bestseller: false,
    dateAdded: "2026-10-22",
    tags: ["filler", "bella", "body", "50 ml"]
  },
  {
    id: "bella-body-60ml-26mg",
    name: "Bella Body HA Filler 26mg/ml (60 ml (26 mg/ml))",
    brand: "bella",
    category: "dermal-fillers",
    subcategory: "Body",
    description: "A concentrated hyaluronic-acid body filler for extensive contouring.",
    image: "https://ueeshop.ly200-cdn.com/u_file/UPBB/UPBB605/2408/21/products/de6b2a61a8.png?x-oss-process=image/quality,q_100/resize,m_lfit,h_640,w_640",
    featured: false,
    bestseller: false,
    dateAdded: "2026-10-27",
    tags: ["filler", "bella", "body", "60 ml (26 mg/ml)"]
  },
  {
    id: "bella-body-100ml-26mg",
    name: "Bella Body HA Filler 26mg/ml (100 ml (26 mg/ml))",
    brand: "bella",
    category: "dermal-fillers",
    subcategory: "Body",
    description: "A large-format concentrated hyaluronic-acid body filler.",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRUggXGWJ3-JIdVVQLnIPkXYpTftTQTr0bq3Ury8xXTHlQTW8_c3ZV2CRFu&s=10",
    featured: false,
    bestseller: false,
    dateAdded: "2026-11-01",
    tags: ["filler", "bella", "body", "100 ml (26 mg/ml)"]
  },
  {
    id: "bella-body-60ml-18mg",
    name: "Bella Body HA Filler 18mg/ml (60 ml (18 mg/ml))",
    brand: "bella",
    category: "dermal-fillers",
    subcategory: "Body",
    description: "A hyaluronic-acid body filler formulated for body contouring.",
    image: "https://ueeshop.ly200-cdn.com/u_file/UPBB/UPBB605/2608/25/products/HA-Body-1.jpg?x-oss-process=image/quality,q_100/resize,m_lfit,h_945,w_945",
    featured: false,
    bestseller: false,
    dateAdded: "2026-01-10",
    tags: ["filler", "bella", "body", "60 ml (18 mg/ml)"]
  },
  {
    id: "bella-plla-stimulator",
    name: "Bella PLLA Stimulator (1 vial)",
    brand: "bella",
    category: "dermal-fillers",
    subcategory: "PLLA Stimulator",
    description: "A poly-L-lactic acid biostimulator for long-lasting collagen stimulation.",
    image: "https://ueeshop.ly200-cdn.com/u_file/UPBB/UPBB605/2608/25/products/PLLA-1.jpg?x-oss-process=image/format,webp/quality,q_100/resize,m_lfit,h_640,w_640",
    gallery: ["https://ueeshop.ly200-cdn.com/u_file/UPBB/UPBB605/2608/25/products/PLLA-5.jpg?x-oss-process=image/format,webp/quality,q_100/resize,m_lfit,h_640,w_640"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-01-15",
    tags: ["filler", "bella", "plla", "collagen stimulator", "1 vial"]
  },
  {
    id: "bella-calcium-filler",
    name: "Bella Calcium Filler (1 vial)",
    brand: "bella",
    category: "dermal-fillers",
    subcategory: "Calcium Hydroxyapatite",
    description: "A calcium-hydroxyapatite filler for structural volumizing and contouring.",
    image: "https://ueeshop.ly200-cdn.com/u_file/UPBB/UPBB605/2412/18/products/photobank3-14c6.jpg?x-oss-process=image/quality,q_100/resize,m_lfit,h_500,w_500",
    gallery: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRbOaAVDnVpSgCXzg1aqkWMpRElbvThYb-pj2yFEN6ylVgeaRgkcejFxA&s=10"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-01-20",
    tags: ["filler", "bella", "calcium hydroxyapatite", "1 vial"]
  },


 // اللي تحت ده برده مفيش صوره لسه
  {
    id: "hadurage-joint-2ml",
    name: "Hadurage Joint Filler (2 ml)",
    brand: "hadurage",
    category: "dermal-fillers",
    subcategory: "Intra-Articular",
    description: "An intra-articular hyaluronic-acid preparation for joint viscosupplementation.",
    image: "",
    gallery: [],
    featured: false,
    bestseller: false,
    dateAdded: "2026-01-25",
    tags: ["joint filler", "intra-articular", "2 ml"]
  },
    // اللي تحت ده برده مفيش صوره لسه
  {
    id: "hadurage-joint-3ml",
    name: "Hadurage Joint Filler (3 ml)",
    brand: "hadurage",
    category: "dermal-fillers",
    subcategory: "Intra-Articular",
    description: "An intra-articular hyaluronic-acid preparation for joint viscosupplementation.",
    image: "",
    gallery: [],
    featured: false,
    bestseller: false,
    dateAdded: "2026-01-30",
    tags: ["joint filler", "intra-articular", "3 ml"]
  },
  {
    id: "hadurage-red-lips-2x1ml",
    name: "Hadurage Red Lips (2 x 1 ml)",
    brand: "hadurage",
    category: "dermal-fillers",
    subcategory: "Lips",
    description: "A hyaluronic-acid filler formulated specifically for lip enhancement.",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRY10WUMeSGdQunqobJchoyfuA2fkfxiozL4fpY-BLW_v9LKt0giUAqjOR_&s=10",
    featured: false,
    bestseller: false,
    dateAdded: "2026-02-04",
    tags: ["filler", "hadurage", "lips", "2 x 1 ml"]
  },
  {
    id: "maxyfill-70cc",
    name: "Maxyfill Body (70 cc)",
    brand: "maxyfill",
    category: "dermal-fillers",
    subcategory: "Body Contouring",
    description: "A large-format hyaluronic-acid gel for extensive body contouring.",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRIwlDDecxFg27TbNf9g2XFsKKJ8ioLdFqToiHCxHi16Q&s=10",
    gallery: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSgFInQ525r9CE8kj3RHcF0rJnZ_nv9ncvD1MZVIh9CLzyBmtsalxn023I&s=10"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-02-09",
    tags: ["filler", "body", "contouring", "70 cc"]
  },

    // اللي تحت ده برده مفيش صوره لسه
  {
    id: "audrey-50ml-h",
    name: "Audrey High Density (50 ml)",
    brand: "audrey",
    category: "dermal-fillers",
    subcategory: "High Density",
    description: "A large-format high-density hyaluronic-acid gel for body contouring.",
    image: "",
    gallery: [],
    featured: false,
    bestseller: false,
    dateAdded: "2026-02-14",
    tags: ["filler", "high density", "body", "50 ml"]
  },
  {
    id: "dermofil-volmatic-2ml",
    name: "Dermofil Volmatic (2 ml)",
    brand: "dermofil",
    category: "dermal-fillers",
    subcategory: "Volmatic",
    description: "A cohesive volumizing gel formulated for structural facial support.",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRAeH4fpRqlA_1EfqTBrIS7MNOGRtMJY3Az3CLScKvVSapMo5LL00BLu2Fy&s=10",
    gallery: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRLPCgZmcj4ihrF7AitGtDiCeqkdD5dQl69l4r0vzdcCLNbiMvnWt1cHpbe&s=10"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-02-19",
    tags: ["filler", "volmatic", "2 ml"]
  },
  {
    id: "master-treat-20ml",
    name: "Master Treat High Volume (20 ml)",
    brand: "master-treat",
    category: "dermal-fillers",
    subcategory: "High Volume",
    description: "A high-volume gel formulated for extensive body contouring.",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQj1eq4DNodHbIjT5qnNu9QB3lzx2MAOMTWkcgPqS0kzw&s=10",
    featured: false,
    bestseller: false,
    dateAdded: "2026-02-24",
    tags: ["filler", "high volume", "body", "20 ml"]
  },
  {
    id: "bde-beaute-60cc",
    name: "BDE Beauté Body (60 cc)",
    brand: "bde-beaute",
    category: "dermal-fillers",
    subcategory: "Body Contouring",
    description: "A large-format body filler for contouring procedures.",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQuMuVNJfi-CoDOMNvC9BhoGKXCx8qMpo67zpTqnb1BHlfW7M1nBwOmF8WC&s=10",
    featured: false,
    bestseller: false,
    dateAdded: "2026-03-01",
    tags: ["filler", "body", "contouring", "60 cc"]
  },
  {
    id: "demure-ultra-20ml-k",
    name: "Demure Ultra K (20 ml)",
    brand: "demure",
    category: "dermal-fillers",
    subcategory: "Ultra",
    description: "A large-format hyaluronic-acid gel for body volumizing and contouring.",
    image: "https://www.demurefiller.com/wp-content/uploads/2026/01/10ml-Ultra-Description-2.jpg",
    gallery: ["https://www.demurefiller.com/wp-content/uploads/2026/01/10ml-Ultra-Description-3.jpg"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-03-06",
    tags: ["filler", "ultra", "body", "20 ml"]
  },
  {
    id: "eptq-s500",
    name: "E.P.T.Q S500 Structural",
    brand: "eptq",
    category: "dermal-fillers",
    subcategory: "Structural",
    description: "A structural collagen-stimulating formulation for long-lasting facial support.",
    image: "https://www.hesupplies.co.uk/cdn/shop/files/e.p.t.q-s500-_2_-54-p.webp?v=1735392417&width=1445",
    gallery: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQw89Jm-tpk9HohZ0UnColCX5VCQyr4Qmh1MCPE4WNpNw&s=10"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-03-11",
    tags: ["filler", "structural", "collagen stimulator", "s500"]
  },
  {
    id: "hyaron-2-5ml",
    name: "Hyaron Sodium Hyaluronate (2.5 ml)",
    brand: "hyaron",
    category: "skin-boosters",
    subcategory: "Sodium Hyaluronate",
    description: "A sodium-hyaluronate skin booster formulated to support hydration and skin quality.",
    image: "https://fyaestheticboutique.co.uk/wp-content/uploads/2026/02/hyaron-scaled-4.jpg",
    gallery: ["https://cosmetix.eu/hpeciai/a0fe385de2d23a407afbfacc41fea23e/eng_pl_Hyaron-2-5ml-433_1_1.jpg"],
    featured: true,
    bestseller: true,
    dateAdded: "2026-03-16",
    tags: ["skin booster", "hyaluronic acid", "hydration", "2.5 ml"]
  },
  {
    id: "aqua-exosome",
    name: "Aqua Exosome Complex (1 vial)",
    brand: "aqua",
    category: "skin-boosters",
    subcategory: "Exosome Complex",
    description: "An exosome-complex skin booster formulated to support skin revitalization.",
    image: "https://westcoastpartners.com/cdn/shop/files/HyalMass_Aqua-Exosome.webp?v=1724073765",
    gallery: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRO5nTjSHL1C5AQQhcFnt2hPdNMk5U7wv4isrSxhaweaE_PQr245qTAi24&s=10"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-03-21",
    tags: ["skin booster", "exosome", "1 vial"]
  },
  {
    id: "exo-active",
    name: "Exo Active Exosomes (1 vial)",
    brand: "exo",
    category: "skin-boosters",
    subcategory: "Exosomes",
    description: "An active exosome preparation formulated for skin revitalization treatments.",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTZ7jN_kxyKQwygISZ4ScRgqh17Z2t702ra38AZcEyJhnRXkuFhOUmj0o&s=10",
    featured: false,
    bestseller: false,
    dateAdded: "2026-03-26",
    tags: ["skin booster", "exosome", "1 vial"]
  },
  {
    id: "regloray-pdrn",
    name: "Regloray PDRN (1 vial)",
    brand: "regloray",
    category: "skin-boosters",
    subcategory: "PDRN Polynucleotide",
    description: "A PDRN (polynucleotide) skin booster formulated to support skin repair and quality.",
    image: "https://www.bsicosmetics.com/wp-content/uploads/2023/11/stayve_beauty_care.jpg",
    featured: false,
    bestseller: false,
    dateAdded: "2026-03-31",
    tags: ["skin booster", "pdrn", "1 vial"]
  },
  {
    id: "mesoheal-amber-glow",
    name: "Mesoheal Amber Glow (1 vial)",
    brand: "mesoheal",
    category: "skin-boosters",
    subcategory: "Succinic Acid + HA",
    description: "A succinic-acid and hyaluronic-acid complex formulated to support skin radiance.",
    image: "https://filler-direct.co.uk/wp-content/uploads/2025/07/Mesoheal%C2%AE-Amber-Glow-10-vials-x-5ml.jpg",
    gallery: ["https://dermarolleronlinestore.co.za/wp-content/uploads/2024/05/Mesoheal_amber_Glow.jpg"],
    featured: false,
    bestseller: true,
    dateAdded: "2026-04-05",
    tags: ["skin booster", "succinic acid", "glow", "1 vial"]
  },

      // اللي تحت ده برده مفيش صوره لسه
  {
    id: "dermofil-super-hydra",
    name: "Dermofil Super Hydra (1 vial)",
    brand: "dermofil",
    category: "skin-boosters",
    subcategory: "Super Hydra Complex",
    description: "A hydration-focused complex skin booster for improved skin moisture retention.",
    image: "",
    gallery: [],
    featured: false,
    bestseller: false,
    dateAdded: "2026-04-10",
    tags: ["skin booster", "hydration", "1 vial"]
  },
  {
    id: "rrs-long-lasting-3ml",
    name: "RRS Long Lasting (3 ml)",
    brand: "rrs",
    category: "skin-boosters",
    subcategory: "HA + Amino Acids",
    description: "A hyaluronic-acid and amino-acid complex formulated for long-lasting skin revitalization.",
    image: "https://en.topdermal.com/wp-content/uploads/2018/06/Y2A7436.jpg",
    gallery: ["https://www.fillermarket.com/1804-large_default/skin-tech-aesthetic-dermal-rrs-ha-long-lasting.jpg"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-04-15",
    tags: ["skin booster", "amino acids", "hyaluronic acid", "3 ml"]
  },
  {
    id: "rrs-hyalift-750-active",
    name: "RRS Hyalift Pro Active (750 mg)",
    brand: "rrs",
    category: "skin-boosters",
    subcategory: "Pure HA",
    description: "A pure hyaluronic-acid skin booster formulated for skin hydration and quality.",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSSYLgrFSWvYqKM6LNgbvP8fvu12sJv54Qc9_x5ZlGOK5zKZoNz7i77a_E&s=10",
    featured: false,
    bestseller: false,
    dateAdded: "2026-04-20",
    tags: ["skin booster", "hyaluronic acid", "750 mg"]
  },

      // اللي تحت ده برده مفيش صوره لسه
  {
    id: "booster-starter-kit",
    name: "Multi-Component Booster Kit (1 kit)",
    brand: "clinic-select",
    category: "skin-boosters",
    subcategory: "Starter Kit",
    description: "A multi-component starter kit for skin-booster treatment sessions.",
    image: "",
    gallery: [],
    featured: false,
    bestseller: false,
    dateAdded: "2026-04-25",
    tags: ["skin booster", "kit", "1 kit"]
  },
  {
    id: "jalupro-super-hydro",
    name: "Jalupro Super Hydro (1 vial)",
    brand: "jalupro",
    category: "skin-boosters",
    subcategory: "HA + Amino Acids + Peptides",
    description: "A hyaluronic-acid, amino-acid and peptide complex for skin revitalization.",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTzETj1d40MvhYg9HqnLj2FUk5CPKqzOv4Bf6oqNNP6ag&s=10",
    gallery: ["https://jolifill.de/cdn/shop/files/JALUPRO-SUPER-HYDRO-2.5ML-PRODUKT-VERPACKUNG.webp?v=1779804849"],
    featured: true,
    bestseller: false,
    dateAdded: "2026-04-30",
    tags: ["skin booster", "amino acids", "peptides", "1 vial"]
  },
  {
    id: "bella-skin-booster-2-20ml",
    name: "Bella Skin Booster (2 ml / 20 ml)",
    brand: "bella",
    category: "skin-boosters",
    subcategory: "Skin Booster",
    description: "A hyaluronic-acid skin booster available in clinic and multi-session formats.",
    image: "https://derma-solution.com/wp-content/uploads/2024/04/bella-b-1.jpg",
    gallery: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQy1gnXjsJaWMSMxkHUyO-yjNJgjwxVcys1HbNa3G4HhCdY_tRPQdY4ky4&s=10"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-05-05",
    tags: ["skin booster", "bella", "2 ml / 20 ml"]
  },
  {
    id: "bella-hl-2ml",
    name: "Bella H+L (2 ml)",
    brand: "bella",
    category: "skin-boosters",
    subcategory: "High & Low HA",
    description: "A dual-molecular-weight (high and low HA) skin booster for layered hydration.",
    image: "https://ueeshop.ly200-cdn.com/u_file/UPBB/UPBB605/2608/25/products/HL-1.jpg?x-oss-process=image/format,webp/quality,q_100/resize,m_lfit,h_640,w_640",
    gallery: ["https://ueeshop.ly200-cdn.com/u_file/UPBB/UPBB605/2608/25/products/HL-5.jpg?x-oss-process=image/format,webp/quality,q_100/resize,m_lfit,h_640,w_640"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-05-10",
    tags: ["skin booster", "bella", "hyaluronic acid", "2 ml"]
  },

      // اللي تحت ده برده مفيش صوره لسه
  {
    id: "hadurage-pdrn-2ml",
    name: "Hadurage PDRN Skin Booster (2 ml)",
    brand: "hadurage",
    category: "skin-boosters",
    subcategory: "PDRN",
    description: "A PDRN skin booster formulated to support skin repair and revitalization.",
    image: "",
    gallery: [],
    featured: false,
    bestseller: false,
    dateAdded: "2026-05-15",
    tags: ["skin booster", "pdrn", "hadurage", "2 ml"]
  },
  {
    id: "nithya-collagen-powder",
    name: "Nithya Collagen Powder (1 vial)",
    brand: "nithya",
    category: "skin-boosters",
    subcategory: "Type I Collagen Powder",
    description: "A type-I collagen powder formulated to support skin structure and quality.",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQUIfAns2Xdgnfp8rrCCx9c3PGvFZDawVYTzG0awZubalW7ISgnQt7dSoz_&s=10",
    gallery: ["https://lipstore.pl/userdata/public/gfx/638/-nithya-kolagen.jpg"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-05-20",
    tags: ["skin booster", "collagen", "1 vial"]
  },

      // اللي تحت ده برده مفيش صوره لسه
  {
    id: "everline-meso-booster",
    name: "Everline Meso-Booster Complex (1 vial)",
    brand: "everline",
    category: "skin-boosters",
    subcategory: "Meso-Booster Complex",
    description: "A multi-active meso-booster complex for skin revitalization sessions.",
    image: "",
    gallery: [],
    featured: false,
    bestseller: false,
    dateAdded: "2026-05-25",
    tags: ["skin booster", "meso-booster", "1 vial"]
  },
  {
    id: "kiara-reju",
    name: "Kiara Reju (1 vial)",
    brand: "kiara",
    category: "skin-boosters",
    subcategory: "PDRN + HA",
    description: "A PDRN and hyaluronic-acid complex formulated for skin rejuvenation.",
    image: "https://www.eleglobals.com/wp-content/uploads/2024/11/kiara-1.png",
    gallery: ["https://cdn11.bigcommerce.com/s-41bfam661h/images/stencil/original/products/358/2233/kiara-reju-skin-booster-3-x-2.2ml-ea-getglowing-skincare__20669.1675617660.jpg?c=1"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-05-30",
    tags: ["skin booster", "pdrn", "hyaluronic acid", "1 vial"]
  },
  {
    id: "rrs-long-lasting-crosslinked",
    name: "RRS Long Lasting Cross-Linked HA (1 vial)",
    brand: "rrs",
    category: "skin-boosters",
    subcategory: "Cross-Linked HA",
    description: "A cross-linked hyaluronic-acid skin booster for extended-duration hydration.",
    image: "https://priormedical.eu/wp-content/uploads/2024/03/RRS-HA-LONG-LASTING_BOXPRIMARY-PACKAGING.jpg",
    featured: false,
    bestseller: false,
    dateAdded: "2026-06-04",
    tags: ["skin booster", "cross-linked", "hyaluronic acid", "1 vial"]
  },
  {
    id: "remedium-pdrn",
    name: "Remedium PDRN (1 vial)",
    brand: "remedium",
    category: "skin-boosters",
    subcategory: "PDRN DNA Extract",
    description: "A PDRN DNA-extract skin booster formulated to support skin repair.",
    image: "https://jolifill.de/cdn/shop/files/REMEDIUM-PDRN-3-X-2_2ML_0dd40043-3139-4872-8eb3-1c28aae6f535.webp?v=1768996346",
    gallery: ["https://jolifill.de/cdn/shop/files/REMEDIUM-PDRN-3-X-2_2ML-SPRITZE-PACKUNG_1beaa4dd-b689-478f-8774-f988e1181b6e.webp?v=1768996346&width=1200"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-06-09",
    tags: ["skin booster", "pdrn", "1 vial"]
  },
  {
    id: "hyalift-750-pro",
    name: "Hyalift 750 Pro (750 mg)",
    brand: "rrs",
    category: "skin-boosters",
    subcategory: "HA",
    description: "A concentrated hyaluronic-acid skin booster for professional use.",
    image: "https://pamiderm.com/media/image/product/938/lg/en-p-rrs-hyalift-75-proactive-6-x-5-ml.webp",
    gallery: ["https://www.skintechpharmagroup.com/media/2019/03/C_RRS-HYALIFT-75-PROACTIVE_Vial_10ml.png"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-06-14",
    tags: ["skin booster", "hyaluronic acid", "750 mg"]
  },
  {
    id: "stem-cell-whitening",
    name: "Stem Cell Whitening Ampoules (1 box)",
    brand: "clinic-select",
    category: "mesotherapy",
    subcategory: "Stem Cell Ampoules",
    description: "Whitening-focused stem-cell ampoules formulated for mesotherapy sessions.",
    image: "https://static.wixstatic.com/media/abc7b0_c7bed56996884df0acf7883cce2a8e84~mv2.jpg/v1/fill/w_480,h_320,al_c,q_80,usm_0.66_1.00_0.01,enc_avif,quality_auto/abc7b0_c7bed56996884df0acf7883cce2a8e84~mv2.jpg",
    featured: false,
    bestseller: false,
    dateAdded: "2026-06-19",
    tags: ["mesotherapy", "whitening", "stem cell", "1 box"]
  },
  {
    id: "bella-meso-pdrn",
    name: "Bella Meso-PDRN (2 ml x 5 vials)",
    brand: "bella",
    category: "mesotherapy",
    subcategory: "PDRN Vials",
    description: "A PDRN vial set formulated for mesotherapy revitalization sessions.",
    image: "https://ueeshop.ly200-cdn.com/u_file/UPBB/UPBB605/2608/25/products/C-PDRN-1.jpg?x-oss-process=image/format,webp/quality,q_100/resize,m_lfit,h_640,w_640",
    gallery: [],
    featured: false,
    bestseller: false,
    dateAdded: "2026-06-24",
    tags: ["mesotherapy", "pdrn", "bella", "2 ml x 5 vials"]
  },
  {
    id: "bella-meso-fullerene",
    name: "Bella Meso-Fullerene (2 ml x 5 vials)",
    brand: "bella",
    category: "mesotherapy",
    subcategory: "Fullerene Vials",
    description: "A fullerene-complex vial set formulated for mesotherapy sessions.",
    image: "https://ueeshop.ly200-cdn.com/u_file/UPBB/UPBB605/2608/25/products/FULLERENE-1.jpg?x-oss-process=image/format,webp/quality,q_100/resize,m_lfit,h_640,w_640",
    gallery: ["https://ueeshop.ly200-cdn.com/u_file/UPBB/UPBB605/2608/25/products/FULLERENE-5-153727926e.jpg?x-oss-process=image/format,webp/quality,q_100/resize,m_lfit,h_640,w_640"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-06-29",
    tags: ["mesotherapy", "fullerene", "bella", "2 ml x 5 vials"]
  },
  {
    id: "bella-meso-vitb12",
    name: "Bella Meso-Vit B12 (2 ml x 5 vials)",
    brand: "bella",
    category: "mesotherapy",
    subcategory: "Vitamin B12 Vials",
    description: "A vitamin B12 vial set formulated for mesotherapy sessions.",
    image: "https://ueeshop.ly200-cdn.com/u_file/UPBB/UPBB605/2608/25/products/VITAMINB12-1.jpg?x-oss-process=image/format,webp/quality,q_100/resize,m_lfit,h_640,w_640",
    gallery: ["https://ueeshop.ly200-cdn.com/u_file/UPBB/UPBB605/2608/25/products/VITAMINB12-5.jpg?x-oss-process=image/format,webp/quality,q_100/resize,m_lfit,h_640,w_640"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-07-04",
    tags: ["mesotherapy", "vitamin b12", "bella", "2 ml x 5 vials"]
  },
  {
    id: "bella-meso-gluta",
    name: "Bella Meso-Gluta (2 ml x 5 vials)",
    brand: "bella",
    category: "mesotherapy",
    subcategory: "Glutathione Vials",
    description: "A glutathione vial set formulated for brightening mesotherapy sessions.",
    image: "https://ueeshop.ly200-cdn.com/u_file/UPBB/UPBB605/2608/25/products/GLUTATHIONE-1.jpg?x-oss-process=image/format,webp/quality,q_100/resize,m_lfit,h_640,w_640",
    gallery: ["https://ueeshop.ly200-cdn.com/u_file/UPBB/UPBB605/2608/25/products/GLUTATHIONE-5.jpg?x-oss-process=image/format,webp/quality,q_100/resize,m_lfit,h_640,w_640"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-07-09",
    tags: ["mesotherapy", "glutathione", "bella", "2 ml x 5 vials"]
  },
  {
    id: "bella-meso-ha18-coll",
    name: "Bella Meso-HA18+Collagen (2 ml x 5 vials)",
    brand: "bella",
    category: "mesotherapy",
    subcategory: "HA + Collagen Vials",
    description: "A hyaluronic-acid and collagen vial set formulated for mesotherapy sessions.",
    image: "https://ueeshop.ly200-cdn.com/u_file/UPBB/UPBB605/2608/25/products/HA18-1.jpg?x-oss-process=image/format,webp/quality,q_100/resize,m_lfit,h_640,w_640",
    gallery: ["https://ueeshop.ly200-cdn.com/u_file/UPBB/UPBB605/2608/25/products/HA18-3.jpg?x-oss-process=image/format,webp/quality,q_100/resize,m_lfit,h_640,w_640"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-07-14",
    tags: ["mesotherapy", "hyaluronic acid", "collagen", "bella", "2 ml x 5 vials"]
  },
  {
    id: "bella-meso-vitc",
    name: "Bella Meso-Vit C (2 ml x 5 vials)",
    brand: "bella",
    category: "mesotherapy",
    subcategory: "Vitamin C Vials",
    description: "A vitamin C vial set formulated for brightening mesotherapy sessions.",
    image: "https://ueeshop.ly200-cdn.com/u_file/UPBB/UPBB605/2608/25/products/VITAMIN-C-1.jpg?x-oss-process=image/format,webp/quality,q_100/resize,m_lfit,h_640,w_640",
    gallery: ["https://ueeshop.ly200-cdn.com/u_file/UPBB/UPBB605/2608/25/products/VITAMIN-C-5.jpg?x-oss-process=image/format,webp/quality,q_100/resize,m_lfit,h_640,w_640"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-07-19",
    tags: ["mesotherapy", "vitamin c", "bella", "2 ml x 5 vials"]
  },
  {
    id: "bella-whitening-exosome",
    name: "Bella Whitening Exosome (1 vial)",
    brand: "bella",
    category: "mesotherapy",
    subcategory: "Exosome Whitening Formula",
    description: "An exosome-based whitening formula for brightening mesotherapy sessions.",
    image: "https://ueeshop.ly200-cdn.com/u_file/UPBB/UPBB605/2608/25/products/1-153859ffce.png?x-oss-process=image/format,webp/quality,q_100/resize,m_lfit,h_640,w_640",
    gallery: ["https://ueeshop.ly200-cdn.com/u_file/UPBB/UPBB605/2608/25/products/3-153907452d.png?x-oss-process=image/format,webp/quality,q_100/resize,m_lfit,h_640,w_640"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-07-24",
    tags: ["mesotherapy", "exosome", "whitening", "bella", "1 vial"]
  },
  {
    id: "bella-hair-growth-exosome",
    name: "Bella Hair Growth Exosome (1 vial)",
    brand: "bella",
    category: "mesotherapy",
    subcategory: "Exosome Hair Complex",
    description: "An exosome-based hair complex formulated for scalp mesotherapy sessions.",
    image: "https://ueeshop.ly200-cdn.com/u_file/UPBB/UPBB605/2608/25/products/Hair-Growth-1.jpg?x-oss-process=image/format,webp/quality,q_100/resize,m_lfit,h_640,w_640",
    gallery: ["https://ueeshop.ly200-cdn.com/u_file/UPBB/UPBB605/2608/25/products/Hair-Growth-3.jpg?x-oss-process=image/format,webp/quality,q_100/resize,m_lfit,h_640,w_640"],
    featured: false,
    bestseller: true,
    dateAdded: "2026-07-29",
    tags: ["mesotherapy", "exosome", "hair", "bella", "1 vial"]
  },

        // اللي تحت ده برده مفيش صوره لسه
  {
    id: "bella-antiacne-exosome",
    name: "Bella Anti-Acne Exosome (1 vial)",
    brand: "bella",
    category: "mesotherapy",
    subcategory: "Exosome Anti-Acne",
    description: "An exosome-based formula formulated for acne-focused mesotherapy sessions.",
    image: "",
    gallery: [],
    featured: false,
    bestseller: false,
    dateAdded: "2026-08-03",
    tags: ["mesotherapy", "exosome", "anti-acne", "bella", "1 vial"]
  },

      // اللي تحت ده برده مفيش صوره لسه
  {
    id: "bella-antiage-exosome",
    name: "Bella Anti-Aging Exosome (1 vial)",
    brand: "bella",
    category: "mesotherapy",
    subcategory: "Exosome Anti-Aging",
    description: "An exosome-based formula formulated for anti-aging mesotherapy sessions.",
    image: "",
    gallery: [],
    featured: false,
    bestseller: false,
    dateAdded: "2026-08-08",
    tags: ["mesotherapy", "exosome", "anti-aging", "bella", "1 vial"]
  },
        // اللي تحت ده برده مفيش صوره لسه
  {
    id: "bella-repair-exosome",
    name: "Bella Repair Exosome (1 vial)",
    brand: "bella",
    category: "mesotherapy",
    subcategory: "Exosome Repairing",
    description: "An exosome-based repairing formula for post-procedure mesotherapy sessions.",
    image: "",
    gallery: [],
    featured: false,
    bestseller: false,
    dateAdded: "2026-08-13",
    tags: ["mesotherapy", "exosome", "repair", "bella", "1 vial"]
  },
        // اللي تحت ده برده مفيش صوره لسه
  {
    id: "hadurage-pdrn-meso",
    name: "Hadurage PDRN Mesotherapy (1 vial)",
    brand: "hadurage",
    category: "mesotherapy",
    subcategory: "PDRN Solution",
    description: "A PDRN solution formulated for mesotherapy revitalization sessions.",
    image: "",
    gallery: [],
    featured: false,
    bestseller: false,
    dateAdded: "2026-08-18",
    tags: ["mesotherapy", "pdrn", "hadurage", "1 vial"]
  },
  {
    id: "hadurage-hair-meso",
    name: "Hadurage Hair Meso (1 vial)",
    brand: "hadurage",
    category: "mesotherapy",
    subcategory: "Hair Growth Solution",
    description: "A hair-growth solution formulated for scalp mesotherapy sessions.",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQC0S8XzLcIaTb-WyDb1C9Rad4YXebW5bzAqfuZqpYekA&s=10",
    gallery: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSVtqMIgNNx0reSE2Xb43zZ_ND1kmpyXvSXxMb6UWlxTg&s=10"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-08-23",
    tags: ["mesotherapy", "hair", "hadurage", "1 vial"]
  },
        // اللي تحت ده برده مفيش صوره لسه
  {
    id: "vitamin-c-ampoules",
    name: "Pure Vitamin C Ampoules (1 box)",
    brand: "clinic-select",
    category: "mesotherapy",
    subcategory: "Vitamin C Ampoules",
    description: "Pure vitamin C ampoules formulated for brightening mesotherapy sessions.",
    image: "",
    gallery: [],
    featured: false,
    bestseller: false,
    dateAdded: "2026-08-28",
    tags: ["mesotherapy", "vitamin c", "1 box"]
  },
        // اللي تحت ده برده مفيش صوره لسه
  {
    id: "glutathione-vials",
    name: "Glutathione Vials (1 box)",
    brand: "clinic-select",
    category: "mesotherapy",
    subcategory: "Glutathione",
    description: "Glutathione vials formulated for brightening mesotherapy sessions.",
    image: "",
    gallery: [],
    featured: false,
    bestseller: false,
    dateAdded: "2026-09-02",
    tags: ["mesotherapy", "glutathione", "1 box"]
  },
  {
    id: "pink-glow-cocktail",
    name: "Pink Glow Cocktail (1 vial)",
    brand: "clinic-select",
    category: "mesotherapy",
    subcategory: "Multi-Ingredient Cocktail",
    description: "A multi-ingredient cocktail formulated for radiance-focused mesotherapy sessions.",
    image: "https://m.media-amazon.com/images/I/61OycJFUv9L.jpg",
    gallery: ["https://resources.facesconsent.com/products-images/17165/809522551-487184229-Pink-Glow-product-photo.jpeg"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-09-07",
    tags: ["mesotherapy", "cocktail", "glow", "1 vial"]
  },
        // اللي تحت ده برده مفيش صوره لسه
  {
    id: "rablanca-peeling",
    name: "Rablanca Peeling Pack Solution (1 kit)",
    brand: "rablanca",
    category: "cold-peeling",
    subcategory: "Peeling Solution",
    description: "A cold peeling-pack solution for surface skin renewal without downtime.",
    image: "",
    gallery: [],
    featured: false,
    bestseller: false,
    dateAdded: "2026-09-12",
    tags: ["peeling", "skin renewal", "1 kit"]
  },
  {
    id: "luer-lock-connector",
    name: "Luer Lock Connector (1 unit)",
    brand: "medisupply",
    category: "disposables",
    subcategory: "Connector",
    description: "A Luer-lock connector for use with injectable aesthetic products.",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR6G4dEXTYZYbgkNyuuE7nQHbPAoqrQvOyIcUb4VGq7oA&s=10",
    featured: false,
    bestseller: false,
    dateAdded: "2026-09-17",
    tags: ["disposable", "accessory", "connector", "1 unit"]
  },
  {
    id: "micro-cannula",
    name: "Micro Cannula (1 unit)",
    brand: "medisupply",
    category: "disposables",
    subcategory: "Cannula",
    description: "A micro-cannula for atraumatic delivery of dermal fillers and skin boosters.",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQtLy-Fa3uZ8893AtdqWOzQdg-xTKY5avvXOMSZeKZ4Q8lbkpYxMRucesc&s=10",
    featured: false,
    bestseller: true,
    dateAdded: "2026-09-22",
    tags: ["disposable", "accessory", "cannula", "1 unit"]
  },
  {
    id: "fine-injection-needles",
    name: "Fine Injection Needles (Box)",
    brand: "medisupply",
    category: "disposables",
    subcategory: "Needles",
    description: "Fine disposable injection needles for precise aesthetic procedures.",
    image: "https://www.chempro.com.au/image/cache/catalog/products/1007682-1-670x670.jpg",
    featured: false,
    bestseller: false,
    dateAdded: "2026-09-27",
    tags: ["disposable", "accessory", "needle", "box"]
  }
];